### ISSUE TITLE
Venona Cluster name length constraint

### ISSUE THREAD

**Issue by andyguerin** [codefresh-io/venona#103]
Hi

We're performing a 'behind the firewall' install of Codefresh runner and hit a block with the error:

"Error: cluster name length is limited to 20"

Our cluster name exceeds this due to company naming standard 

Is there a reason the length is constrained? 

Venona version used: 0.30.5

**Comment by callum-tait-pbx** [comment]
Facing a similar issue here, the default EKS cluster name is longer than 20 characters, currently testing the solution so ultimately this may not be a problem however it seems like an unnecessary restriction?
