### ISSUE TITLE
v1.x.x missing file error

### ISSUE THREAD

**Issue by SpainTrain** [codefresh-io/venona#140]
To get the 1.x.x install directions working (`codefresh install agent --kube-namespace codefresh --install-runtime`), I had to first run `touch .Codefresh/agent/venona`.  Appears to have worked after creating that empty file.

**Comment by olegsu** [comment]
Thanks @SpainTrain 
What is the codefresh cli version you are using? (`codefresh version`)

**Comment by SpainTrain** [comment]
```
spain@cloudshell:~ (mr-ci-cd)$ codefresh version
client version: 0.64.6
```

**Comment by oren-codefresh** [comment]
Thanks @SpainTrain 
I was unable to reproduce this issue, I've deleted the agent folder and also the .Codefresh folder as well. I'll keep an eye on this issue. If you have any more details on it please share them here.
Thanks again
Oren
