### ISSUE TITLE
venona help should exit 0

### ISSUE THREAD

**Issue by osterman** [codefresh-io/venona#22]
## what
* Running `venona help` results in non-zero exit code
* Running `venona` shouldn't write to file system without user permission (which is why I assume it works when I run it as root)

![image](https://user-images.githubusercontent.com/52489/52702406-ec3f0700-2f30-11e9-9bdb-e50fa9437773.png)

## why
* I think it happens if `venona` is executed in a non-writable directory

**Comment by olegsu** [comment]
Thanks @osterman 
The reason is that it tries to read codefresh yaml, which may not exist.

**Comment by olegsu** [comment]
Fix pushed #27
