### ISSUE TITLE
If I chose "ebs-csi" these settings fall back to the default

### ISSUE THREAD

**Issue by elocke** [codefresh-io/venona#310]
https://github.com/codefresh-io/venona/blob/041f016c0e989689c1fccd1efbc1cc6a122bfcb9/.deploy/cf-runtime/templates/volume-provisioner/storageclass.dind-volume-provisioner.vp.yaml#L28

If I choose "ebs-csi" as the type, then all these values fall back to the default ones.

**Comment by mikhail-klimko** [comment]
@elockem 
Set `ebs-csi` at `.Values.storage.backend`
```yaml
storage:
  backend: ebs-csi
```
