### ISSUE TITLE
Error to install runner when using tolerations

### ISSUE THREAD

**Issue by tiago-cesar** [codefresh-io/venona#343]
After #338 I can't install the runner through the CLI if I use a `values.yaml` file with tolerations enabled:

`codefresh runner init --values my-values.yaml`

I got:
`Cannot deserialize kuberentes object daemonset.dind-lv-monitor.vp.yaml: yaml: line 28: did not find expected key
Error: yaml: line 28: did not find expected key
Error: Failed to install runtime: Component exited with status code 1`

I suppose [these](https://github.com/codefresh-io/venona/blob/release-1.0/venonactl/pkg/templates/kubernetes/daemonset.dind-lv-monitor.vp.yaml#L27-L28) lines could be in the wrong place.
Could you check, please?
Thanks!

**Comment by mikhail-klimko** [comment]
@tiago-cesar Can you please share `my-values.yaml` content?

**Comment by tiago-cesar** [comment]
@mikhail-klimko  Thanks for your quick answer. Here is the `my-values.yaml` file content (with fake sensitive values):
[my-values.txt](https://github.com/codefresh-io/venona/files/11183592/my-values.txt)

I was using local volumes so this file was generating a broken daemonset manifest. I switched to ebs and since it doesn't create the daemonset, the runner installation ran as expected.
