### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by kostis-codefresh** [codefresh-io/venona#44]
Just downloaded venona

`> venona version                                            

Date: 2019-04-22T13:24:31Z                                  

Commit: f703dd58881ab43b094ea15ce4c620d506409f33            

Local Version: 0.24.0                                        

Latest version: 0.24.0                                      

                                                           

Kostis@NOMAD-PRO C:\workspace\docs.codefresh.io              

> venona status                                              

Error reading file                                          

panic: runtime error: invalid memory address or nil pointer d

[signal 0xc0000005 code=0x0 addr=0x20 pc=0x127060c]          

                                                           

goroutine 1 [running]:                                      

github.com/codefresh-io/venona/venonactl/cmd.glob..func4(0x23

       /codefresh/volume/venona/venonactl/cmd/status.go:78 +

github.com/spf13/cobra.(*Command).execute(0x2355240, 0x237fdd

       /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:

github.com/spf13/cobra.(*Command).ExecuteC(0x2354fe0, 0x0, 0x

       /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:

github.com/spf13/cobra.(*Command).Execute(...)              

       /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:

github.com/codefresh-io/venona/venonactl/cmd.Execute()      

       /codefresh/volume/venona/venonactl/cmd/root.go:32 +0x

main.main()                                                  

       /codefresh/volume/venona/venonactl/main.go:20 +0x27  `

**Comment by dankirkpatrick** [comment]
I had this same problem... I installed the codefresh CLI using npm, and the problem appears to have been fixed.  Hope this helps other people.
