### ISSUE TITLE
Provide YAML manifests

### ISSUE THREAD

**Issue by nesl247** [codefresh-io/venona#45]
Please provide yaml manifests (at minimum helm charts) that can be used. The companies that would be uses the behind-the-firewall (venona) setup are likely to be using IaC (Infrastructure as Code).

**Comment by olegsu** [comment]
Hey @nesl247 
Helm charts (using helm2) is not an option.
The installation process is not straightforward and requires more complex flow. 
Helm3 should support that flow, anyway, I think adding a Kubernetes manifest with documentation should be good enoght to run IaC.
Also there is a docker image with [venona-cli](https://hub.docker.com/r/codefresh/venonacli) .

**Comment by nesl247** [comment]
I actually only said helm because from my experience, projects only seem to be willing to do helm charts and that’s it. I’m actually only looking for standard manifest files so I can import them with Pulumi.

**Comment by olegsu** [comment]
@nesl247 
https://github.com/codefresh-contrib/runner-manual-install
