### ISSUE TITLE
Allow imageRegistry override for runtime.engine.runtimeImages

### ISSUE THREAD

**Issue by drewburr** [codefresh-io/venona#473]
When defining `global.imageRegistry`, the values in `runtime.engine.runtimeImages` are not updated to reflect this setting. It does not appear that an option has been provided to support this override. Is this something that could be supported?

We have an internal registry that proxies quay.io. Using the internal registry is preferred in all cases as we consistently exceed quay.io's historical uptime values.

[Permalink](https://github.com/codefresh-io/venona/blob/2c0a8688a11a737553d01ad4f4afbf1e095ce999/charts/cf-runtime/values.yaml#L521-L534)

**Comment by mikhail-klimko** [comment]
Hey @drewburr !

When you set `global.imageRegistry`, the registry prefix ends up in runtime environment spec here:
https://github.com/codefresh-io/venona/blob/2c0a8688a11a737553d01ad4f4afbf1e095ce999/charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml#L24-L34
https://github.com/codefresh-io/venona/blob/2c0a8688a11a737553d01ad4f4afbf1e095ce999/charts/cf-runtime/templates/runtime/_helpers.tpl#L36-L43
