### ISSUE TITLE
Support PodNodeSelector

### ISSUE THREAD

**Issue by kpurdon** [codefresh-io/venona#54]
I'm happy to take a stab at contributing this, but wanted to make sure it was something you'd accept first.

I'd like to be able to instal all codefresh resources on a specific set of nodes. This is done (one way) via a node selector. https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector

The idea would be to run `venona install --node-selector "foo:bar"` which would then install all resources on only nodes with the label foo and value bar.

**Comment by dustinvanbuskirk** [comment]
Yes we will accept outside contributions on the project.

Just follow the normal contibution style of fork, commit and submit Pull Request for review.
