### ISSUE TITLE
Venona install fails on v1.16 Kubernetes clusters

### ISSUE THREAD

**Issue by dankirkpatrick** [codefresh-io/venona#73]
The apiVersion "extensions/v1beta1" is no longer supported in v1.16 Kubernetes (it was deprecated in v1.8).  It should be replaced with "apps/v1".

Venona install currently attempts to install a "venona" deployment with the unsupported apiVersion and fails.

**Comment by olegsu** [comment]
@dankirkpatrick thank you.
Will update in the comming week

**Comment by oren-codefresh** [comment]
Should work on 0.28.5
